language: go

go:
  - 1.13.x
  - 1.14.x

env:
  - GO111MODULE=on

git:
  depth: 1

services:
  - postgresql

before_script:
  - psql -c 'create database testdb;' -U postgres

script:
  - go test github.com/satoukick/webserver/server -race -coverprofile=coverage.txt -covermode=atomic

after_script:
  - bash <(curl -s https://codecov.io/bash)
