// Code generated by protoc-gen-go. DO NOT EDIT.
// source: db_request.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ToDoQueryRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ToDoQueryRequest) Reset()         { *m = ToDoQueryRequest{} }
func (m *ToDoQueryRequest) String() string { return proto.CompactTextString(m) }
func (*ToDoQueryRequest) ProtoMessage()    {}
func (*ToDoQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_34f65abd230cefca, []int{0}
}

func (m *ToDoQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ToDoQueryRequest.Unmarshal(m, b)
}
func (m *ToDoQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ToDoQueryRequest.Marshal(b, m, deterministic)
}
func (m *ToDoQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ToDoQueryRequest.Merge(m, src)
}
func (m *ToDoQueryRequest) XXX_Size() int {
	return xxx_messageInfo_ToDoQueryRequest.Size(m)
}
func (m *ToDoQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ToDoQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ToDoQueryRequest proto.InternalMessageInfo

func (m *ToDoQueryRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ToDoQueryResponse struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Completed            bool     `protobuf:"varint,2,opt,name=completed,proto3" json:"completed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ToDoQueryResponse) Reset()         { *m = ToDoQueryResponse{} }
func (m *ToDoQueryResponse) String() string { return proto.CompactTextString(m) }
func (*ToDoQueryResponse) ProtoMessage()    {}
func (*ToDoQueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_34f65abd230cefca, []int{1}
}

func (m *ToDoQueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ToDoQueryResponse.Unmarshal(m, b)
}
func (m *ToDoQueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ToDoQueryResponse.Marshal(b, m, deterministic)
}
func (m *ToDoQueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ToDoQueryResponse.Merge(m, src)
}
func (m *ToDoQueryResponse) XXX_Size() int {
	return xxx_messageInfo_ToDoQueryResponse.Size(m)
}
func (m *ToDoQueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ToDoQueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ToDoQueryResponse proto.InternalMessageInfo

func (m *ToDoQueryResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ToDoQueryResponse) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

func init() {
	proto.RegisterType((*ToDoQueryRequest)(nil), "proto.ToDoQueryRequest")
	proto.RegisterType((*ToDoQueryResponse)(nil), "proto.ToDoQueryResponse")
}

func init() { proto.RegisterFile("db_request.proto", fileDescriptor_34f65abd230cefca) }

var fileDescriptor_34f65abd230cefca = []byte{
	// 160 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x48, 0x49, 0x8a, 0x2f,
	0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53,
	0x4a, 0x4a, 0x5c, 0x02, 0x21, 0xf9, 0x2e, 0xf9, 0x81, 0xa5, 0xa9, 0x45, 0x95, 0x41, 0x10, 0x05,
	0x42, 0x7c, 0x5c, 0x4c, 0x99, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xac, 0x41, 0x4c, 0x99, 0x29,
	0x4a, 0xee, 0x5c, 0x82, 0x48, 0x6a, 0x8a, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0x44, 0xb8, 0x58,
	0x4b, 0x32, 0x4b, 0x72, 0x52, 0xc1, 0xea, 0x38, 0x83, 0x20, 0x1c, 0x21, 0x19, 0x2e, 0xce, 0xe4,
	0xfc, 0xdc, 0x82, 0x9c, 0xd4, 0x92, 0xd4, 0x14, 0x09, 0x26, 0x05, 0x46, 0x0d, 0x8e, 0x20, 0x84,
	0x80, 0x91, 0x3f, 0x17, 0xb7, 0x8b, 0x13, 0xdc, 0x28, 0x21, 0x07, 0x2e, 0x4e, 0x04, 0x47, 0x1c,
	0xe2, 0x2e, 0x3d, 0x74, 0xd7, 0x48, 0x49, 0x60, 0x4a, 0x40, 0x9c, 0xa0, 0xc4, 0x90, 0xc4, 0x06,
	0x96, 0x32, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x57, 0xb5, 0xb1, 0x42, 0xdf, 0x00, 0x00, 0x00,
}
